### ISSUE TITLE
PositionTypes erstellen

### ISSUE THREAD

**Issue by crykn** [eskalon/ProjektGG#22]
﻿**Alle Ämtertypen erstellen**

### Details
Die geplanten [Ämtertypen](https://github.com/eskalon/ProjektGG/wiki/Amtsübersicht) als JSON-Dateien erstellen und in der `PositionTypes`-Klasse laden. Außerdem die bereits bestehenden PositionTypes auf den neusten Stand bringen. Als Lohn könnten folgende Werte verwendet werden: 150, 300, 450, 750, 950, 1200, 1500, 1800, 2300. Außerdem muss noch geklärt werden, ob der Public Vote bei den Stadträten sinnvoll ist.

<br>

Ein Beispiel für eine der JSON-Dateien:
```json
{
	"name": "Bürgermeister",
	"cabinet": 4,
	"level": 6,
	"popularVote": false,
	"statusRequirementIndex": 2,
	"salary": 1200
}
```

### Aufgaben 
- [x] Die JSON-Files im _/assets/data/positions/_-Ordner erstellen; dazu die Klassen-Variablen der `PositionType`-Klasse betrachten (!); grds. sollte jede Klassenvariable in der JSON-Datei gesetzt werden
- [x] Die bereits bestehende Datei für den Bürgermeister auf den neusten Stand bringen
- [x] Die JSON-Files in der `PositionTypes`-Klasse laden lassen (dazu einfach am `MAYOR` orientieren)

**Comment by Vlarabor** [comment]
Added json-files for all authorities and updated the major.json file.
